name: HungerGamesDoDo
main: KaitoDoDo\HungerGames\HungerGames
author: KaitoDoDo
version: 4.0.0
api: 
- 1.0.0
- 1.1.0
- 2.0.0

commands:
    hg:
        usage: /hg <leave-make>
        description: HungerGames-Commands
    lang:
        usage: /lang <en>
        description: HungerGames-EnglishLanguage
    setrank:
        usage: /setrank
        description: HungerRanks-Commands
    start:
        description: HungerGames-ForceStart
